name: Publish netherlands.mbtiles

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

permissions:
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: Fast

    steps:
    - uses: actions/checkout@v3

    - name: Build mbiltes
      run: ./quickstart.sh netherlands

    - name: Upload tiles to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: data/netherlands.mbtiles
        asset_name: netherlands.mbtiles
        tag: ${{ github.ref }}
        overwrite: true
